# This task verifies that "postgresql_pgstatements_agent" and "postgres_exporter" are present in the
# "pmm-admin list" command's output and have "Running" status
#
# Task adjustments are handled by parent playbook vars:
#             var "port_flag"      :  to access agent with custom port
#                                     ex: port_flag: "--pmm-agent-listen-port={{ custom_port }}"
#
- name: set empty port_flag
  set_fact:
    port_flag: ""
  when: port_flag is not defined

- name: Validate postgresql_pgstatements_agent status
  block:
    - shell: "pmm-admin list {{ port_flag }} | grep 'postgresql_pgstatements_agent' | awk -F' ' '{print $2}'"
      register: pgstatements_agent_status
    - assert:
        that:
          - "'Running' in pgstatements_agent_status.stdout"
        fail_msg: "postgresql_pgstatements_agent status is not 'Running'!"
        success_msg: "postgresql_pgstatements_agent is Running"
  rescue:
    - ansible.builtin.debug:
        msg: postgresql_pgstatements_agent status is {{ pgstatements_agent_status.stdout }}

- name: Validate postgres_exporter_status status
  block:
    - name: Wait for postgres_exporter to have Running Status.
      shell: "pmm-admin list {{ port_flag }} | grep 'postgres_exporter' | awk -F' ' '{print $2}'"
      register: postgres_exporter_status
      until: postgres_exporter_status.stdout.find('Running') != -1
      delay: 5
      retries: 5
  rescue:
    - name: Print the postgres_exporter status
      ansible.builtin.debug:
        msg: postgres_exporter status is {{ postgres_exporter_status.stdout }}
