---
# Advanced package test:
#   prepare Percona Repository and software
#   install PMM client deb/rpm
#   perform correct setup
#   setup PS 5.7
#   setup PSMDB 4.4
#   setup PGSQL 13
#   verify versions, metrics, exporters, etc.

- hosts: all
  become: true
  become_method: sudo
  connection: local
  vars:
    pmm_server_address: "{{ lookup('env', 'PMM_SERVER_IP') }}"
    pmm_server_password: "{{ lookup('env', 'ADMIN_PASSWORD') | default('admin', true) }}"
    test_repo: "{{ lookup('env', 'install_repo') }}"
    metrics_mode: "{{ lookup('env', 'METRICS_MODE') | default('auto', true) }}"
    pmm_version: "{{ lookup('env', 'PMM_VERSION') | regex_search('\\S(.*\\S)?') }}"

  tasks:
  - name: Register Instance IP
    shell: echo $(ip route get 8.8.8.8 | awk -F"src " 'NR==1{split($2,a," ");print a[1]}')
    register: instance_ip

  - name: Register Instance IP as a variable
    set_fact:
      instance_ip: "{{ instance_ip.stdout }}"

  - name: Set Integrations list
    set_fact:
      enabled_db: "{{ db_list|select|list }}"
    vars:
      db_list:
        - "{{ (false) | ternary('ps-8.0','') }}"
        - "{{ (ansible_os_family == 'RedHat' and ansible_distribution_major_version < '9') | ternary('ps-5.7','') }}"
        - "{{ (ansible_os_family == 'Debian') | ternary('ps-5.7','') }}"
        - psmdb-6.0
        - "{{ (ansible_os_family == 'Debian') | ternary('pg-13','') }}"
        - "{{ (ansible_os_family == 'RedHat' and ansible_distribution_major_version < '8') | ternary('pg-13','') }}"

  - name: Setup environment
    include_tasks: ../tasks/pmm2_client_test_prepare.yml

### install pmm2-client
  - name: Install PMM client new deb packages
    apt: name=pmm2-client update_cache=yes state=latest
    when: ansible_os_family == "Debian"

  - name: Install PMM client new rpm packages
    yum: name=pmm2-client state=latest
    when: ansible_os_family == "RedHat"

  - name: Check that PMM Client version is correct
    include_tasks: ../tasks/verify_pmm_client_version.yml

### Setup PMM Client
  - name: Use "pmm-admin config" to connect pmm client to server
    shell: pmm-admin config --force --server-insecure-tls --metrics-mode={{ metrics_mode }} --server-url=https://admin:{{ pmm_server_password }}@{{ pmm_server_address }} {{ instance_ip }} generic node_{{ instance_ip }}

  - name: Check that PMM client version is correct
    include_tasks: ../tasks/verify_pmm_status_versions.yml

### start PS 5.7
  - name: Install and start Percona Server 5.7
    include_tasks: ../tasks/start_ps57.yml
    when: '"ps-5.7" in enabled_db'

  - name: Check if Metric Endpoint with Auth works for Mysqld Exporter
    shell: "bash -x ../scripts/pmm2_check_metric.sh --service_name mysql_{{ instance_ip }} --metric_name mysql_up --pmm_server_ip {{pmm_server_address}} --agent_type mysqld_exporter --metric_value 1"
    environment:
      ADMIN_PASSWORD: "{{ pmm_server_password }}"
    when: '"ps-5.7" in enabled_db'
## end PS 5.7

### start PSMDB 6.0
  - name: Install and start Percona Server MongoDB 6.0
    include_tasks: ../tasks/install_and_setup_psmdb_60.yml

  - name: Check MongoDB Exporter metric endpoint with Auth(including service with socket)
    shell: "{{item}}"
    with_items:
      - "bash -x ../scripts/pmm2_check_metric.sh --service_name mongodb_{{ instance_ip }} --metric_name mongodb_up --pmm_server_ip {{pmm_server_address}} --agent_type mongodb_exporter --metric_value 1"
      - "bash -x ../scripts/pmm2_check_metric.sh --service_name mongodb_socket_{{ instance_ip }} --metric_name mongodb_up --pmm_server_ip {{pmm_server_address}} --agent_type mongodb_exporter --metric_value 1"
    environment:
      ADMIN_PASSWORD: "{{ pmm_server_password }}"

  - name: Remove mongodb service from monitoring which was added via socket
    command: pmm-admin remove mongodb mongodb_socket_{{ instance_ip }}
### end PSMDB 6.0

### start PGSQL 13
  - name: Install and start Percona Server MongoDB 4.4
    include_tasks: ../tasks/start_pgsql13.yml
    when: '"pg-13" in enabled_db'

  - name: Check Postgres Exporter metric endpoint with Auth works
    shell: "{{item}}"
    retries: 3
    delay: 10
    with_items:
      - bash -x ../scripts/pmm2_check_metric.sh --service_name pgsql_{{ instance_ip }} --metric_name pg_up{collector=\"\custom_query.hr\"\} --pmm_server_ip {{pmm_server_address}} --agent_type postgres_exporter --metric_value 1
      - bash -x ../scripts/pmm2_check_metric.sh --service_name pgsql_{{ instance_ip }} --metric_name pg_up{collector=\"\custom_query.lr\"\} --pmm_server_ip {{pmm_server_address}} --agent_type postgres_exporter --metric_value 1
      - bash -x ../scripts/pmm2_check_metric.sh --service_name pgsql_{{ instance_ip }} --metric_name pg_up{collector=\"\custom_query.mr\"\} --pmm_server_ip {{pmm_server_address}} --agent_type postgres_exporter --metric_value 1
      - bash -x ../scripts/pmm2_check_metric.sh --service_name pgsql_{{ instance_ip }} --metric_name pg_up{collector=\"\exporter\"\} --pmm_server_ip {{pmm_server_address}} --agent_type postgres_exporter --metric_value 1
    environment:
      ADMIN_PASSWORD: "{{ pmm_server_password }}"
    when: '"pg-13" in enabled_db'

  - name: Check Postgres Exporter metric endpoint with Auth works(service added via socket)
    shell: "{{item}}"
    retries: 3
    delay: 10
    with_items:
      - bash -x ../scripts/pmm2_check_metric.sh --service_name pgsql_socket_{{ instance_ip }} --metric_name pg_up{collector=\"\custom_query.hr\"\} --pmm_server_ip {{pmm_server_address}} --agent_type postgres_exporter --metric_value 1
      - bash -x ../scripts/pmm2_check_metric.sh --service_name pgsql_socket_{{ instance_ip }} --metric_name pg_up{collector=\"\custom_query.lr\"\} --pmm_server_ip {{pmm_server_address}} --agent_type postgres_exporter --metric_value 1
      - bash -x ../scripts/pmm2_check_metric.sh --service_name pgsql_socket_{{ instance_ip }} --metric_name pg_up{collector=\"\custom_query.mr\"\} --pmm_server_ip {{pmm_server_address}} --agent_type postgres_exporter --metric_value 1
      - bash -x ../scripts/pmm2_check_metric.sh --service_name pgsql_socket_{{ instance_ip }} --metric_name pg_up{collector=\"\exporter\"\} --pmm_server_ip {{pmm_server_address}} --agent_type postgres_exporter --metric_value 1
    environment:
      ADMIN_PASSWORD: "{{ pmm_server_password }}"
    when: '"pg-13" in enabled_db'

  - name: Remove PostgreSQL instances added via socket
    command: pmm-admin remove postgresql pgsql_socket_{{ instance_ip }}
    when: '"pg-13" in enabled_db'
### end PG

### verifications
  - name: Check pmm2-client files
    include_tasks: ../tasks/verify_pmm_client_files.yml

  - name: Parse and set PMM minor version
    shell: "pmm-admin --version | grep -oP '(?<=[.])\\w+(?=[.])' | head -1"
    register: pmm_agent_minor_version

  - name: Set Exporters to check
    set_fact:
      exporters_check: "{{ ex_list|select|list }}"
    vars:
      ex_list:
        - vmagent
        - node_exporter
        - "{{ ('ps-' in enabled_db | join('')) | ternary('mysqld_exporter','') }}"
        - "{{ ('psmdb-' in enabled_db | join('')) | ternary('mongodb_exporter','') }}"
        - "{{ ('pg-' in enabled_db | join('')) | ternary('postgres_exporter','') }}"

  - name: Include Exporters Port in output checks for 2.29.0+
    include_tasks: ../tasks/exporter-port-output-checks.yml
    when: pmm_agent_minor_version.stdout | int >= 29
    loop: "{{ exporters_check }}"

  - name: Validate node_exporter status
    block:
      - name: Wait for node_exporter to be Running
        shell: pmm-admin list | grep node_exporter | awk -F" " '{print $2}'
        register: node_exporter_status
        until: node_exporter_status.stdout.find('Running') != -1
        delay: 5
        retries: 5
    rescue:
      - name: Print the node_exporter Status
        ansible.builtin.debug:
          msg: node_exporter status is {{ node_exporter_status.stdout }}

  - name: Check Node Exporter metric endpoint with Auth works
    shell: "bash -x ../scripts/pmm2_check_metric.sh --metric_name node_textfile_scrape_error --pmm_server_ip {{pmm_server_address}} --agent_type node_exporter --metric_value 0"
    environment:
      ADMIN_PASSWORD: "{{ pmm_server_password }}"
    retries: 3
    delay: 10

  - name: Validate vmagent status
    block:
      - name: Wait for vmagent to be Running
        shell: pmm-admin list | grep vmagent | awk -F" " '{print $2}'
        register: vmagent_status
        until: vmagent_status.stdout.find('Running') != -1
        delay: 5
        retries: 5
    rescue:
      - name: Print the vmagent status
        ansible.builtin.debug:
          msg: vmagent status is {{ vmagent_status.stdout }}

  - name: Check 'postgresql_pgstatements_agent' and 'postgres_exporter' are Running
    include_tasks: ../tasks/verify_pg_exporter_and_agent.yml
    when: '"pg-" in enabled_db | join("")'
